
export default function TeamStorage() {
    return [
        {
            id: 0,
            name: "Matthew Cabral",
            role: "Co-President",
            year: "U2",
            image: '',
            program: "Software Engineering",
            linkedin: "/",
            website: "https://matthew-cabral.com",
            description: "hey how are u, im a munin",
        },
        {
            id: 1,
            name: "Matthew Cabral",
            role: "Co-President",
            year: "U2",
            image: '',
            program: "Software Engineering",
            linkedin: "/",
            website: "https://matthew-cabral.com",
            description: "hey how are u, im a munin",
        },
        {
            id: 2,
            name: "Matthew Cabral",
            role: "Co-President",
            year: "U2",
            image: '',
            program: "Software Engineering",
            linkedin: "/",
            website: "https://matthew-cabral.com",
            description: "hey how are u, im a munin",
        },
        {
            id: 3,
            name: "Matthew Cabral",
            role: "Co-President",
            year: "U2",
            image: '',
            program: "Software Engineering",
            linkedin: "/",
            website: "https://matthew-cabral.com",
            description: "hey how are u, im a munin",
        },
        {
            id: 4,
            name: "Matthew Cabral",
            role: "Co-President",
            year: "U2",
            image: '',
            program: "Software Engineering",
            linkedin: "/",
            website: "https://matthew-cabral.com",
            description: "hey how are u, im a munin",
        },
        {
            id: 5,
            name: "Matthew Cabral",
            role: "Co-President",
            year: "U2",
            image: '',
            program: "Software Engineering",
            linkedin: "/",
            website: "https://matthew-cabral.com",
            description: "hey how are u, im a munin",
        },
        {
            id: 6,
            name: "Matthew Cabral",
            role: "Co-President",
            year: "U2",
            image: '',
            program: "Software Engineering",
            linkedin: "/",
            website: "https://matthew-cabral.com",
            description: "hey how are u, im a munin",
        },
        {
            id: 7,
            name: "Matthew Cabral",
            role: "Co-President",
            year: "U2",
            image: '',
            program: "Software Engineering",
            linkedin: "/",
            website: "https://matthew-cabral.com",
            description: "hey how are u, im a munin",
        },
        {
            id: 8,
            name: "Matthew Cabral",
            role: "Co-President",
            year: "U2",
            image: '',
            program: "Software Engineering",
            linkedin: "/",
            website: "https://matthew-cabral.com",
            description: "hey how are u, im a munin",
        },
        {
            id: 9,
            name: "Matthew Cabral",
            role: "Co-President",
            year: "U2",
            image: '',
            program: "Software Engineering",
            linkedin: "/",
            website: "https://matthew-cabral.com",
            description: "hey how are u, im a munin",
        },
        {
            id: 10,
            name: "Matthew Cabral",
            role: "Co-President",
            year: "U2",
            image: '',
            program: "Software Engineering",
            linkedin: "/",
            website: "https://matthew-cabral.com",
            description: "hey how are u, im a munin",
        },
        {
            id: 11,
            name: "Matthew Cabral",
            role: "Co-President",
            year: "U2",
            image: '',
            program: "Software Engineering",
            linkedin: "/",
            website: "https://matthew-cabral.com",
            description: "hey how are u, im a munin",
        },

    ];
}